# Generated by Django 5.1.2 on 2024-11-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='name',
            field=models.CharField(default='ram', max_length=100),
            preserve_default=False,
        ),
    ]
