# Generated by Django 5.1.2 on 2024-11-03 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_chatsessionmodel_chatstoragemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatsessionmodel',
            old_name='client',
            new_name='user_one',
        ),
        migrations.RenameField(
            model_name='chatsessionmodel',
            old_name='talent',
            new_name='user_two',
        ),
    ]
