# Generated by Django 5.1.2 on 2024-11-04 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_client_chatsessionmodel_user_one_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatstoragemodel',
            name='message',
        ),
        migrations.RemoveField(
            model_name='chatstoragemodel',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='chatstoragemodel',
            name='user',
        ),
    ]
