# Generated by Django 5.1.2 on 2024-11-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_chatstoragemodel_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='otp',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='otp_verification',
            field=models.BooleanField(default=False),
        ),
    ]
